//! CLI command modules

#[cfg(feature = "gmail")]
pub mod auth;
#[cfg(feature = "calendar")]
pub mod calendar;
#[cfg(feature = "chat")]
pub mod chat;
#[cfg(feature = "people")]
pub mod contacts;
#[cfg(feature = "gmail")]
pub mod drafts;
#[cfg(feature = "drive")]
pub mod drive;
#[cfg(feature = "forms")]
pub mod forms;
#[cfg(feature = "gmail")]
pub mod history;
#[cfg(feature = "gmail")]
pub mod import;
#[cfg(feature = "gmail")]
pub mod labels;
#[cfg(feature = "gmail")]
pub mod message_ops;
#[cfg(feature = "gmail")]
pub mod messages;
#[cfg(feature = "gmail")]
pub mod profile;
#[cfg(feature = "gmail")]
pub mod send;
#[cfg(feature = "gmail")]
pub mod send_as;
#[cfg(feature = "gmail")]
pub mod thread_ops;
#[cfg(feature = "gmail")]
pub mod transport;
#[cfg(feature = "gmail")]
pub mod watch;
